
management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employeedb?createDatabaseIfNotExist=true
    username: root
    password: root123


  jpa:
    hibernate:
      ddl-auto: create
      database-platform=org:
        hibernate:
          dialect:
            MySQLDialect: