
management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employeedb?createDatabaseIfNotExist=true
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    dialect: org.hibernate.dialect.MySQL8Dialect
server:
  port: 0
security:
  oauth2:
    resource:
      token-info-uri: http://localhost:8282/oauth/check_token
client:
  client-id: web
  client-password : webpass
